import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Jalaswap',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <img className='top-0 absolute z-1 bg-repeat-y' src='/images/jalaswap-landing-page-bg.svg'/>
        <div className='absolute z-20 w-full pb-10 overflow-x-hidden'>{children}</div>
      </body>
    </html>
  )
}
