import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Kayen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <div className="bg-bg-main text-white font-medium flex flex-col justify-start items-center">
          {children}
        </div>
      </body>
    </html>
  )
}
