export const DISCORD_LINK = "https://discord.gg/2GxuJvbQA6"
export const X_LINK = "https://twitter.com/KAYEN_Protocol"
export const MEDIUM_LINK = "https://medium.com/@kayen-protocol"
export const GIUTUB_LINK = "https://github.com/Kayen-Protocol/"
export const SWAP_PRODUCT_LINK = "https://app.kayen.org/KayenSwap/swap"